[package]
name = "TradingPlatform"
version = "1.0.0"
authors = []

[addresses]
ContractAddr = "0xe5f8ca3d03b48d89d88b5224d15ba5d0b191abdb1dcde8d447f91ce4f9dc394e"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
