[package]
name = "TradingPlatform"
version = "1.0.0"
authors = []

[addresses]
ContractAddr = "0xfcb48b0167d6c03f20fb227cf9cf02c5269a1439b6598a69886ae4e799aea7d6"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
